# Importing the libraries

In [33]:
import numpy as np
import pandas as pd
import seaborn as sns

%matplotlib inline
import matplotlib.pyplot as plt

from sklearn.preprocessing import OneHotEncoder, LabelEncoder, StandardScaler

# Loading the data

In [2]:
df = pd.read_csv("Curstomer Chrun.csv")

In [3]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 360 entries, 0 to 359
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        360 non-null    object
 1   gender            360 non-null    object
 2   SeniorCitizen     360 non-null    int64
 3   Partner           360 non-null    object
 4   Dependents        360 non-null    object
 5   tenure            360 non-null    int64
 6   PhoneService      360 non-null    object
 7   MultipleLines     360 non-null    object
 8   InternetService   360 non-null    object
 9   OnlineSecurity    360 non-null    object
 10  OnlineBackup      360 non-null    object
 11  DeviceProtection  360 non-null    object
 12  TechSupport       360 non-null    object
 13  StreamingTV       360 non-null    object
 14  StreamingMovies   360 non-null    object
 15  Contract          360 non-null    object
 16  PaperlessBilling  360 non-null    object
 17  PaymentMethod     360 non-null    object
 18  MonthlyCharges    360 non-null    float64
 19  TotalCharges      360 non-null    float64
 20  Churn             359 non-null    object
dtypes: float64(2), int64(2), object(17)
memory usage: 59.2+ KB

# Feature engineering

In [5]:
df['tenure'].unique()

array([ 1, 34,  2, 45,  8, 22, 10, 28, 62, 13, 16, 58, 49, 25, 69, 52, 71,
       21, 12, 30, 47, 72, 17, 27,  5, 46, 11, 70, 63, 43, 15, 60, 18, 66,
        9,  3, 31, 50, 64, 56,  7, 42, 35, 48, 29, 65, 38, 68, 32, 55, 37,
       36, 41,  6,  4, 33, 67, 23, 57, 61, 14, 20, 53, 40, 59, 24, 44, 19,
       54, 51], dtype=int64)

In [7]:
# 1. Binning Tenure

# Define bins and labels
bins = [0, 12, 24, 36, 48, 60, np.inf]
labels = ['0-12', '13-24', '25-36', '37-48', '49-60', '60+']

# Create a binned column
df['Tenure_Group'] = pd.cut(df['tenure'], bins=bins, labels=labels)

In [8]:
df['Tenure_Group'].value_counts()

Tenure_Group
0-12     115
60+       72
13-24     56
25-36     43
37-48     37
49-60     37
Name: count, dtype: int64

In [9]:
df['Tenure_Group'].isnull().sum()

0

In [10]:
# 2. Binning Monthly Charges

# Define bins and labels
bins = [0, 20, 40, 60, 80, 100, float('inf')]
labels = ['Very Low', 'Low', 'Medium', 'Medium-to-high', 'High', 'Very High']

# Create a binned column
df['MonthlyCharges_Binned'] = pd.cut(df['MonthlyCharges'], bins=bins, labels=labels)

In [11]:
df['MonthlyCharges_Binned'].value_counts()

MonthlyCharges_Binned
High              89
Medium-to-high    77
Medium            65
Low               58
Very High         46
Very Low          25
Name: count, dtype: int64

In [12]:
df['MonthlyCharges_Binned'].isnull().sum()

0

In [13]:
# 3. Create 'AverageMonthlyCharge' feature
df['AverageMonthlyCharge'] = df['TotalCharges'] / df['tenure'].replace(0, np.nan)

In [14]:
df['AverageMonthlyCharge'].unique()

array([ 29.85      ,  55.57352941,  54.075     ,  40.90555556,
        75.825     , 102.5625    ,  88.60909091,  30.19      ,
       108.7875    ,  56.25725806,  45.18846154,  20.425     ,
        97.95      , 102.78163265, 107.442     , 114.42246377,
        19.67211538, 103.97535211,  52.835     ,  88.70952381,
        39.65      ,  16.85416667,  20.15      ,  60.43275862,
        60.61836735,  51.02      , 101.04574468,  30.2       ,
        88.46458333,  64.3       ,  95.30915493,  90.825     ,
        69.42407407,  20.2       ,  45.25      , 100.71805556,
        63.38      ,  77.13695652, 104.38970588, 100.49090909,
        47.57      ,  69.605     ,  24.60294118,  77.16587302,
        75.49615385,  79.72857143,  48.5       ,  72.075     ,
        81.11153846,  61.65362319,  89.27325581,  95.09333333,
        70.106     ,  79.1625    ,  74.2725    ,  97.36388889,
       100.17777778, 107.21742424,  26.30294118, 109.07916667,
       100.15106383,  90.845     ,  41.13888889,  53.17222222,
        95.25      ,  81.36666667,  77.66702128,  80.55483871,
        18.618     ,  88.735     ,  49.05      ,  20.97403846,
       110.921875  ,  22.97741935,  59.13333333, 109.63392857,
        58.45326087,  60.28125   ,  70.37666667,  27.03555556,
        79.35      ,  51.39545455,  70.98571429, 103.03571429,
        19.86428571, 102.08333333,  63.29857143,  22.02083333,
        20.15434783,  34.80172414,  85.67333333,  74.7       ,
        86.57954545, 109.33846154, 103.59791667,  77.27916667,
        66.88309859,  22.77      ,  21.29230769, 100.58      ,
        19.45      ,  94.88421053,  45.86742424, 111.93897059,
        20.04      , 101.43125   ,  28.9890625 ,  91.19302326,
        18.93402778,  95.25272727,  58.50480769,  91.95581395,
        77.51756757,  53.4921875 ,  82.8       ,  31.2875    ,
       106.465     ,  20.3695122 ,  79.68888889,  98.49017857,
        18.79166667,  76.51666667,  50.05      ,  15.725     ,
        91.7469697 ,  79.09259259,  23.94375   ,  19.75      ,
        56.13169014,  93.51153846,  60.106     ,  48.65820896,
        35.45      ,  40.625     ,  27.63255814,  77.32608696,
        19.96484375,  20.53596491,  70.45      ,  89.24513889,
        70.45625   ,  97.88934426,  82.64140625,  24.73521127,
        98.71846154,  20.45      ,  45.65      ,  64.33166667,
        71.42666667,  70.54375   ,  93.64285714, 113.29357143,
        84.11693548,  18.91666667,  82.34285714,  82.81590909,
        19.08636364,  64.        ,  25.16      ,  58.81153846,
        79.6175    ,  67.6       ,  74.68396226,  21.26363636,
        19.76014493,  68.25      ,  86.86736111,  45.71034483,
        20.0875    ,  82.30813953, 121.4       ,  84.41071429,
        94.34339623,  20.4546875 ,  22.94705882,  76.38      ,
        71.94285714, 103.95      ,  20.52459016,  29.95      ,
        45.3       ,  82.83125   ,  74.34242424,  85.51153846,
        24.8       ,  51.1925    ,  27.38333333,  18.83076923,
        59.4775    ,  73.79883721,  88.5       ,  19.93333333,
       112.90694444,  20.21525424,  95.0825    ,  24.475     ,
       110.50423729, 111.68958333,  20.75      ,  99.30185185,
        79.45      , 104.3028169 ,  79.53461538,  67.24886364,
        81.35909091,  58.04444444,  79.9       , 101.81315789,
       103.9703125 ,  42.25      ,  25.25      ,  18.4295082 ,
        18.62241379,  85.90652174,  60.30614035,  43.60833333,
        57.41212121,  81.91538462,  78.075     ,  67.0875    ,
        25.87183099,  44.8375    ,  18.27916667,  53.69791667,
        82.12096774,  55.2       ,  90.77166667,  87.38829787,
       106.6787037 ,  94.95      ,  84.6       ,  21.7625    ,
        24.20689655,  57.05      ,  29.905     ,  72.55277778,
       101.84545455,  17.771875  ,  88.20138889, 109.42083333,
        77.74756098,  94.24846154,  56.25384615,  68.35      ,
        61.75121951,  71.62      ,  48.55      , 102.34404762,
        90.57941176,  73.575     ,  40.2       ,  82.290625  ,
        19.305     ,  61.25223881, 114.88770492, 115.822     ,
        40.275     ,  42.36724138,  44.06666667, 104.94615385,
        86.40964912,  49.03548387, 111.82777778,  90.60245902,
        23.905     , 105.64473684,  18.63728814,  24.40774648,
        94.45      ,  60.52894737, 108.6025    ,  70.6       ,
        80.22      , 108.17019231,  63.8       ,  55.13928571,
        48.95      ,  53.81666667,  49.825     ,  25.4       ,
        54.23161765,  98.88611111,  81.07272727,  46.3575    ,
        70.        ,  75.81875   ,  43.54      ,  71.3625    ,
        57.74857143,  84.3826087 ,  94.63333333,  18.3625    ,
        20.25      ,  76.56971831,  98.21428571,  75.39375   ,
        73.6       ,  65.64347826,  99.025     ,  89.1625    ,
        60.42647059,  82.67631579,  23.63653846,  71.9796875 ,
        70.84137931,  98.46973684,  76.71770833,  19.25      ,
        85.73863636, 113.83953488,  68.32      ,  83.11      ,
       111.49803922,  19.08591549,  80.49078947,  92.96041667,
        92.46714286,  80.55740741,  59.22222222,  44.8       ,
        46.92222222,  60.53188406,  98.80961538,  80.00454545,
        69.525     ,  34.77321429,  86.47352941,  21.12428571,
        20.24375   ,  96.15108696,  73.03571429,  77.9       ,
        77.85220588, 110.69418605,  90.41838235,  99.04583333,
       104.80952381,  57.190625  ,  87.65915493,  68.31287879,
        21.08174603,  21.09756098,  72.1       ,  84.1       ,
        18.62142857,  43.34130435, 100.4828125 ,  61.58783784,
        40.08235294,  82.05      ,  92.975     ,  40.0047619 ,
        55.5625    , 106.615625  ,  29.81851852,  95.61904762])

In [15]:
# 3. Create 'Revenue_Contribution' feature
df['Revenue_Contribution'] = df['MonthlyCharges'] * df['tenure']

In [16]:
df['Revenue_Contribution'].value_counts()

Revenue_Contribution
20.20      3
24.80      2
830.25     2
1996.40    2
29.85      1
          ..
846.65     1
1002.50    1
1117.80    1
269.55     1
4078.20    1
Name: count, Length: 355, dtype: int64

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 360 entries, 0 to 359
Data columns (total 25 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   customerID             360 non-null    object
 1   gender                 360 non-null    object
 2   SeniorCitizen          360 non-null    int64
 3   Partner                360 non-null    object
 4   Dependents             360 non-null    object
 5   tenure                 360 non-null    int64
 6   PhoneService           360 non-null    object
 7   MultipleLines          360 non-null    object
 8   InternetService        360 non-null    object
 9   OnlineSecurity         360 non-null    object
 10  OnlineBackup           360 non-null    object
 11  DeviceProtection       360 non-null    object
 12  TechSupport            360 non-null    object
 13  StreamingTV            360 non-null    object
 14  StreamingMovies        360 non-null    object
 15  Contract               360 non-null    object
 16  PaperlessBilling       360 non-null    object
 17  PaymentMethod          360 non-null    object
 18  MonthlyCharges         360 non-null    float64
 19  TotalCharges           360 non-null    float64
 20  Churn                  359 non-null    object
 21  Tenure_Group           360 non-null    category
 22  MonthlyCharges_Binned  360 non-null    category
 23  AverageMonthlyCharge   360 non-null    float64
 24  Revenue_Contribution   360 non-null    float64
dtypes: category(2), float64(4), int64(2), object(17)
memory usage: 65.9+ KB

# Performing One-Hot encoding

In [17]:
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

In [19]:
categorical_features = ['gender', 'Partner', 'Dependents', 'MultipleLines', 'InternetService',
                        'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies',
                       'Contract', 'PaperlessBilling', 'PaymentMethod', 'PhoneService']

In [20]:
len(categorical_features)

15

In [21]:
encoded_categories = encoder.fit_transform(df[categorical_features])

In [22]:
encoded_categories

array([[1., 0., 0., ..., 0., 1., 0.],
       [0., 1., 1., ..., 1., 0., 1.],
       [0., 1., 1., ..., 1., 0., 1.],
       ...,
       [0., 1., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 0., 1.]])

In [23]:
# Convert the encoded columns back to a DataFrame
encoded_df = pd.DataFrame(encoded_categories, columns=encoder.get_feature_names_out(categorical_features))

In [24]:
encoded_df

,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,Dependents_Yes,MultipleLines_No,MultipleLines_No phone service,MultipleLines_Yes,InternetService_DSL,...,Contract_One year,Contract_Two year,PaperlessBilling_No,PaperlessBilling_Yes,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,PhoneService_No,PhoneService_Yes
0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
1,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
2,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
3,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
4,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
356,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
357,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
358,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
359,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0

In [25]:
df[~((df['Churn'] == 'Yes') | (df['Churn'] == 'No'))]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,Tenure_Group,MonthlyCharges_Binned,AverageMonthlyCharge,Revenue_Contribution
359,9833-TGFHX,Male,0,Yes,Yes,42,Yes,Yes,Fiber optic,Yes,...,One year,No,Electronic check,97.1,4016.0,NaN,37-48,High,95.619048,4078.2

In [26]:
# Since, only one record has NaN value, we can drop it
df.drop(index=359, inplace=True)

In [27]:
# Drop the original categorical columns from the dataset
df = df.drop(categorical_features, axis=1)

In [28]:
df_encoded = pd.concat([df, encoded_df], axis=1)

In [29]:
df_encoded

,customerID,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,Churn,Tenure_Group,MonthlyCharges_Binned,AverageMonthlyCharge,Revenue_Contribution,...,Contract_One year,Contract_Two year,PaperlessBilling_No,PaperlessBilling_Yes,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,PhoneService_No,PhoneService_Yes
0,7590-VHVEG,0.0,1.0,29.85,29.85,No,0-12,Low,29.850000,29.85,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
1,5575-GNVDE,0.0,34.0,56.95,1889.50,No,25-36,Medium,55.573529,1936.30,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
2,3668-QPYBK,0.0,2.0,53.85,108.15,Yes,0-12,Medium,54.075000,107.70,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
3,7795-CFOCW,0.0,45.0,42.30,1840.75,No,37-48,Medium,40.905556,1903.50,...,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
4,9237-HQITU,0.0,2.0,70.70,151.65,Yes,0-12,Medium-to-high,75.825000,141.40,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,4572-DVCGN,0.0,10.0,80.25,846.00,Yes,0-12,High,84.600000,802.50,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
356,3351-NGXYI,1.0,16.0,54.10,889.00,No,13-24,Medium,55.562500,865.60,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
357,8984-EYLLL,0.0,64.0,105.25,6823.40,No,60+,Very High,106.615625,6736.00,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
358,9057-MSWCO,1.0,27.0,30.75,805.10,Yes,25-36,Low,29.818519,830.25,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
359,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0

In [30]:
print(df_encoded.iloc[359])

customerID                                 NaN
SeniorCitizen                              NaN
tenure                                     NaN
MonthlyCharges                             NaN
TotalCharges                               NaN
Churn                                      NaN
Tenure_Group                               NaN
MonthlyCharges_Binned                      NaN
AverageMonthlyCharge                       NaN
Revenue_Contribution                       NaN
gender_Female                              0.0
gender_Male                                1.0
Partner_No                                 0.0
Partner_Yes                                1.0
Dependents_No                              0.0
Dependents_Yes                             1.0
MultipleLines_No                           0.0
MultipleLines_No phone service             0.0
MultipleLines_Yes                          1.0
InternetService_DSL                        0.0
InternetService_Fiber optic                1.0
InternetService_No                         0.0
OnlineSecurity_No                          0.0
OnlineSecurity_No internet service         0.0
OnlineSecurity_Yes                         1.0
OnlineBackup_No                            1.0
OnlineBackup_No internet service           0.0
OnlineBackup_Yes                           0.0
DeviceProtection_No                        1.0
DeviceProtection_No internet service       0.0
DeviceProtection_Yes                       0.0
TechSupport_No                             1.0
TechSupport_No internet service            0.0
TechSupport_Yes                            0.0
StreamingTV_No                             0.0
StreamingTV_No internet service            0.0
StreamingTV_Yes                            1.0
StreamingMovies_No                         0.0
StreamingMovies_No internet service        0.0
StreamingMovies_Yes                        1.0
Contract_Month-to-month                    0.0
Contract_One year                          1.0
Contract_Two year                          0.0
PaperlessBilling_No                        1.0
PaperlessBilling_Yes                       0.0
PaymentMethod_Bank transfer (automatic)    0.0
PaymentMethod_Credit card (automatic)      0.0
PaymentMethod_Electronic check             1.0
PaymentMethod_Mailed check                 0.0
PhoneService_No                            0.0
PhoneService_Yes                           1.0
Name: 359, dtype: object

In [31]:
df_encoded.drop(index=359, inplace=True)

In [32]:
df_encoded.shape, df_encoded.isnull().sum()

((359, 51),
 customerID                                 0
 SeniorCitizen                              0
 tenure                                     0
 MonthlyCharges                             0
 TotalCharges                               0
 Churn                                      0
 Tenure_Group                               0
 MonthlyCharges_Binned                      0
 AverageMonthlyCharge                       0
 Revenue_Contribution                       0
 gender_Female                              0
 gender_Male                                0
 Partner_No                                 0
 Partner_Yes                                0
 Dependents_No                              0
 Dependents_Yes                             0
 MultipleLines_No                           0
 MultipleLines_No phone service             0
 MultipleLines_Yes                          0
 InternetService_DSL                        0
 InternetService_Fiber optic                0
 InternetService_No                         0
 OnlineSecurity_No                          0
 OnlineSecurity_No internet service         0
 OnlineSecurity_Yes                         0
 OnlineBackup_No                            0
 OnlineBackup_No internet service           0
 OnlineBackup_Yes                           0
 DeviceProtection_No                        0
 DeviceProtection_No internet service       0
 DeviceProtection_Yes                       0
 TechSupport_No                             0
 TechSupport_No internet service            0
 TechSupport_Yes                            0
 StreamingTV_No                             0
 StreamingTV_No internet service            0
 StreamingTV_Yes                            0
 StreamingMovies_No                         0
 StreamingMovies_No internet service        0
 StreamingMovies_Yes                        0
 Contract_Month-to-month                    0
 Contract_One year                          0
 Contract_Two year                          0
 PaperlessBilling_No                        0
 PaperlessBilling_Yes                       0
 PaymentMethod_Bank transfer (automatic)    0
 PaymentMethod_Credit card (automatic)      0
 PaymentMethod_Electronic check             0
 PaymentMethod_Mailed check                 0
 PhoneService_No                            0
 PhoneService_Yes                           0
 dtype: int64)

# Feature scaling

In [34]:
numerical_features = ['tenure', 'MonthlyCharges', 'TotalCharges']

In [35]:
scaler = StandardScaler()

In [36]:
df_encoded[numerical_features] = scaler.fit_transform(df_encoded[numerical_features])

In [37]:
print(df_encoded[numerical_features])

       tenure  MonthlyCharges  TotalCharges
0   -1.240847       -1.229192     -0.998573
1    0.103981       -0.300615     -0.142629
2   -1.200094       -0.406836     -0.962534
3    0.552257       -0.802595     -0.165068
4   -1.200094        0.170527     -0.942512
..        ...             ...           ...
354 -0.425800       -0.816301     -0.625638
355 -0.874076        0.497757     -0.622923
356 -0.629561       -0.398269     -0.603131
357  1.326552        1.354378      2.128303
358 -0.181286       -1.198354     -0.641748

[359 rows x 3 columns]

In [38]:
df_encoded

,customerID,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,Churn,Tenure_Group,MonthlyCharges_Binned,AverageMonthlyCharge,Revenue_Contribution,...,Contract_One year,Contract_Two year,PaperlessBilling_No,PaperlessBilling_Yes,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,PhoneService_No,PhoneService_Yes
0,7590-VHVEG,0.0,-1.240847,-1.229192,-0.998573,No,0-12,Low,29.850000,29.85,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
1,5575-GNVDE,0.0,0.103981,-0.300615,-0.142629,No,25-36,Medium,55.573529,1936.30,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
2,3668-QPYBK,0.0,-1.200094,-0.406836,-0.962534,Yes,0-12,Medium,54.075000,107.70,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
3,7795-CFOCW,0.0,0.552257,-0.802595,-0.165068,No,37-48,Medium,40.905556,1903.50,...,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
4,9237-HQITU,0.0,-1.200094,0.170527,-0.942512,Yes,0-12,Medium-to-high,75.825000,141.40,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
354,0623-IIHUG,1.0,-0.425800,-0.816301,-0.625638,Yes,13-24,Medium,40.004762,879.90,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
355,4572-DVCGN,0.0,-0.874076,0.497757,-0.622923,Yes,0-12,High,84.600000,802.50,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
356,3351-NGXYI,1.0,-0.629561,-0.398269,-0.603131,No,13-24,Medium,55.562500,865.60,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
357,8984-EYLLL,0.0,1.326552,1.354378,2.128303,No,60+,Very High,106.615625,6736.00,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
358,9057-MSWCO,1.0,-0.181286,-1.198354,-0.641748,Yes,25-36,Low,29.818519,830.25,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0

In [39]:
df_encoded['BothStreamingServices'] = ((df_encoded['StreamingTV_Yes'] == 1) & (df_encoded['StreamingMovies_Yes'] == 1)).astype(int)

# Performing label encoding

In [40]:
label_encoder = LabelEncoder()

In [41]:
binned_features = ['Tenure_Group', 'MonthlyCharges_Binned']

In [46]:
df_encoded['Tenure_Group'] = label_encoder.fit_transform(df_encoded['Tenure_Group'])

In [47]:
df_encoded['MonthlyCharges_Binned'] = label_encoder.fit_transform(df_encoded['MonthlyCharges_Binned'])

In [48]:
df_encoded['Tenure_Group'].value_counts()

Tenure_Group
0    115
5     72
1     56
2     43
4     37
3     36
Name: count, dtype: int64

In [49]:
df_encoded['MonthlyCharges_Binned'].value_counts()

MonthlyCharges_Binned
0    88
3    77
2    65
1    58
4    46
5    25
Name: count, dtype: int64

In [50]:
df_encoded.isnull().sum()

customerID                                 0
SeniorCitizen                              0
tenure                                     0
MonthlyCharges                             0
TotalCharges                               0
Churn                                      0
Tenure_Group                               0
MonthlyCharges_Binned                      0
AverageMonthlyCharge                       0
Revenue_Contribution                       0
gender_Female                              0
gender_Male                                0
Partner_No                                 0
Partner_Yes                                0
Dependents_No                              0
Dependents_Yes                             0
MultipleLines_No                           0
MultipleLines_No phone service             0
MultipleLines_Yes                          0
InternetService_DSL                        0
InternetService_Fiber optic                0
InternetService_No                         0
OnlineSecurity_No                          0
OnlineSecurity_No internet service         0
OnlineSecurity_Yes                         0
OnlineBackup_No                            0
OnlineBackup_No internet service           0
OnlineBackup_Yes                           0
DeviceProtection_No                        0
DeviceProtection_No internet service       0
DeviceProtection_Yes                       0
TechSupport_No                             0
TechSupport_No internet service            0
TechSupport_Yes                            0
StreamingTV_No                             0
StreamingTV_No internet service            0
StreamingTV_Yes                            0
StreamingMovies_No                         0
StreamingMovies_No internet service        0
StreamingMovies_Yes                        0
Contract_Month-to-month                    0
Contract_One year                          0
Contract_Two year                          0
PaperlessBilling_No                        0
PaperlessBilling_Yes                       0
PaymentMethod_Bank transfer (automatic)    0
PaymentMethod_Credit card (automatic)      0
PaymentMethod_Electronic check             0
PaymentMethod_Mailed check                 0
PhoneService_No                            0
PhoneService_Yes                           0
BothStreamingServices                      0
dtype: int64

In [51]:
df_encoded.to_csv(r"C:\Users\khush\Documents\ML Ex\Assignment\Encoded Customer Churn.csv")

In [52]:
df_encoded

,customerID,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,Churn,Tenure_Group,MonthlyCharges_Binned,AverageMonthlyCharge,Revenue_Contribution,...,Contract_Two year,PaperlessBilling_No,PaperlessBilling_Yes,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,PhoneService_No,PhoneService_Yes,BothStreamingServices
0,7590-VHVEG,0.0,-1.240847,-1.229192,-0.998573,No,0,1,29.850000,29.85,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0
1,5575-GNVDE,0.0,0.103981,-0.300615,-0.142629,No,2,2,55.573529,1936.30,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0
2,3668-QPYBK,0.0,-1.200094,-0.406836,-0.962534,Yes,0,2,54.075000,107.70,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0
3,7795-CFOCW,0.0,0.552257,-0.802595,-0.165068,No,3,2,40.905556,1903.50,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0
4,9237-HQITU,0.0,-1.200094,0.170527,-0.942512,Yes,0,3,75.825000,141.40,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
354,0623-IIHUG,1.0,-0.425800,-0.816301,-0.625638,Yes,1,2,40.004762,879.90,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0
355,4572-DVCGN,0.0,-0.874076,0.497757,-0.622923,Yes,0,0,84.600000,802.50,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0
356,3351-NGXYI,1.0,-0.629561,-0.398269,-0.603131,No,1,2,55.562500,865.60,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0
357,8984-EYLLL,0.0,1.326552,1.354378,2.128303,No,5,4,106.615625,6736.00,...,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1
358,9057-MSWCO,1.0,-0.181286,-1.198354,-0.641748,Yes,2,1,29.818519,830.25,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0